// <auto-generated />
namespace MVC_Prices2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(type));
        
        string IMigrationMetadata.Id
        {
            get { return "202008191230013_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
