// <auto-generated />
namespace MVC_Prices2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class formData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(formData));
        
        string IMigrationMetadata.Id
        {
            get { return "202011071906495_formData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
