// <auto-generated />
namespace MVC_Prices2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class glassType2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(glassType2));
        
        string IMigrationMetadata.Id
        {
            get { return "202009171434472_glassType2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
