// <auto-generated />
namespace MVC_Prices2.Migrations2
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class profil : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(profil));
        
        string IMigrationMetadata.Id
        {
            get { return "202007160908213_profil"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
